dist: trusty
language: cpp
if: (branch =~ ^(dev|beta|master|test_ci)$) || (tag =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$)
services:
  - docker
matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - TARGET_ARCH=amd64
    - os: osx
      osx_image: xcode9
      env:
        - TARGET_ARCH=i386
    - os: linux
      env:
        - TARGET_ARCH=amd64
    - os: linux
      env:
        - TARGET_ARCH=i386
    - os: linux
      env:
        - TARGET_ARCH=arm
    - os: linux
      env:
        - TARGET_ARCH=arm64
    - os: linux
      env:
        - TARGET_ARCH=mips
    - os: linux
      env:
        - TARGET_ARCH=mips64
cache: ccache
addons:
  apt:
    packages:
      - ccache
      - unzip
  homebrew:
    packages:
      - xz
      - unzip
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    rvm install ruby-2.4.0;
    rvm --default use 2.4.0;
    ruby -v;
    brew update;
    fi
install:
  - git submodule init
  - git submodule update
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install ccache;
    export PATH="/usr/local/opt/ccache/libexec:$PATH";
    brew install xz;
    fi
script:
  - echo "${TARGET_ARCH}"
  - ./.travis/build.sh
  - if [[ -z $TRAVIS_TAG && $TRAVIS_BRANCH != "beta" ]]; then
    ./.travis/test.sh;
    else
    ./.travis/release.sh;
    fi
before_deploy:
  - if [[ -z $TRAVIS_TAG ]]; then
    export TRAVIS_TAG=$(git describe --match "v[0-9]*.[0-9]*.[0-9]*");
    fi
  - export GIT_COMMIT_SHORTCUTS=$(git log --format=%h -1)
  - echo "$TRAVIS_TAG" "$GIT_COMMIT_SHORTCUTS"
deploy:
  - provider: releases
    api_key:
      secure: H2uzjYeu66zNVa8WeMdWFY+cV8nQDuTZpq2XJCHz5eRBcPu4O7hgiA2ArcuVMZFr7v8TxniTuhEt3ymhoMbv9Ja7UtgSTK4GeDdx6l4a1npHn9bKVoTc0POQV0w/ySsDmmOa5IhaMZqiEfvwQXjhJGJJaP/JGC1+GfvPWd8z6hTH46nfpiEjDeNgWySz0WrvzBrcqVNAPGlko8CwrVQVbFu53HF673rdKr6ofJuhBDzRAcg7xZ9mfBonyrzpzI5cwXMhRzf7AaIxpXn2vjiHmiIXcxEtF77tqP9QV8bB3BTZiTEbtv/seWTOJvWCDI+V3ZdnrHE2DYatNP8tSfSBvEA2GSKHmfOLFT31g9JJThV6tGsMQEzk9k8xMq0AfL3bmzUacDVQ5xu5TGPgT7vsa+ajrrXf7v5NyB9IL/hzlJLI0eUnt+wD39tICb5iwyCLvK9GgVew7qi7BcTBOEWNuNQuPTFBR/GmI0uG2CkyhAqnAuxbd7+vxjYXCUKUfdStLENHXZbZBvio7eN6fI/nVyJWpDdeAxe3nVODv27o0h/6hDJxH/dJlgUHVqkZqT8ooQSuMx/oPL/EDJCnPl/O+jQlMwjTOeBTRBSbKCHVJaF4ZhMCyZfs5OYFjHBEgVekKg7v0ujaA8jbnqmEImOc8mrG4FquNu16l949feAV4eM=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      repo: richardo2016/fxjs
  - provider: releases
    name: ${TRAVIS_TAG}-beta
    body: Automated release from Travis CI on beta (${TRAVIS_COMMIT})
    prerelease: true
    api_key:
      secure: H2uzjYeu66zNVa8WeMdWFY+cV8nQDuTZpq2XJCHz5eRBcPu4O7hgiA2ArcuVMZFr7v8TxniTuhEt3ymhoMbv9Ja7UtgSTK4GeDdx6l4a1npHn9bKVoTc0POQV0w/ySsDmmOa5IhaMZqiEfvwQXjhJGJJaP/JGC1+GfvPWd8z6hTH46nfpiEjDeNgWySz0WrvzBrcqVNAPGlko8CwrVQVbFu53HF673rdKr6ofJuhBDzRAcg7xZ9mfBonyrzpzI5cwXMhRzf7AaIxpXn2vjiHmiIXcxEtF77tqP9QV8bB3BTZiTEbtv/seWTOJvWCDI+V3ZdnrHE2DYatNP8tSfSBvEA2GSKHmfOLFT31g9JJThV6tGsMQEzk9k8xMq0AfL3bmzUacDVQ5xu5TGPgT7vsa+ajrrXf7v5NyB9IL/hzlJLI0eUnt+wD39tICb5iwyCLvK9GgVew7qi7BcTBOEWNuNQuPTFBR/GmI0uG2CkyhAqnAuxbd7+vxjYXCUKUfdStLENHXZbZBvio7eN6fI/nVyJWpDdeAxe3nVODv27o0h/6hDJxH/dJlgUHVqkZqT8ooQSuMx/oPL/EDJCnPl/O+jQlMwjTOeBTRBSbKCHVJaF4ZhMCyZfs5OYFjHBEgVekKg7v0ujaA8jbnqmEImOc8mrG4FquNu16l949feAV4eM=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    skip_cleanup: true
    overwrite: true
    on:
      branch: beta
      repo: richardo2016/fxjs
