#!/bin/bash

usage()
{
	echo ""
	echo "Usage: `basename $0` [options] [-jn] [-v] [-h]"
	echo "Options:"
	echo "  release, debug: "
	echo "      Specifies the build type."
	echo "  clean: "
	echo "      Clean the build folder."
	echo "  -h, --help:"
	echo "      Print this message and exit."
	echo ""
	exit 0
}

HOST_OS=`uname`
HOST_ARCH=`uname -m`

case ${HOST_ARCH} in
	i386|i686) HOST_ARCH="i386"
		;;
	x86_64|amd64) HOST_ARCH="amd64"
		;;
	armv6|armv7|armv7s|armv7l) HOST_ARCH="arm"
		;;
	aarch64) HOST_ARCH="arm64"
		;;
	mips|mipsel) HOST_ARCH="mips"
		;;
	mips64) HOST_ARCH="mips64"
		;;
	powerpc) HOST_ARCH="ppc"
		;;
	ppc64) HOST_ARCH="ppc64"
		;;
esac

TARGET_OS=$HOST_OS
TARGET_ARCH=$HOST_ARCH
BUILD_TYPE="release"

for i in "$@"
do
	case $i in
		i386|amd64|arm|arm64|mips|mips64|ppc|ppc64) TARGET_ARCH=$i
			;;
		release|debug|clean) BUILD_TYPE=$i
			;;
		ci) CI="ci"
			;;
		-j*) ENABLE_JOBS=1; BUILD_JOBS="${i#-j}"
			;;
		-v) BUILD_VERBOSE='VERBOSE=1'
			;;
        --help|-h) usage
			;;
		  *) echo "illegal option $i"
			usage
			;;
	esac
done

if [ "$ENABLE_JOBS" = "1" -a "$BUILD_JOBS" = "" ]; then
	#get cpu core count 
	CPU_CORE=1
	case ${HOST_OS} in
		Darwin)
			CPU_CORE=$(sysctl hw.ncpu | awk '{print $2}')
			;;
		Linux)
			CPU_CORE=$(cat /proc/cpuinfo | grep processor | wc -l)
			;;
		Windows)
			CPU_CORE=$(echo $NUMBER_OF_PROCESSORS)
			;;
	esac
	echo "host machine has ${CPU_CORE} core"

	if [ "$CPU_CORE" = "1" ]; then
		BUILD_JOBS=""
	else
		# set build jobs with cpu core count
		BUILD_JOBS=${CPU_CORE}
	fi
fi

ROOT_PATH=`pwd`
FXJS_LIB_CMAKELIST_PATH=${ROOT_PATH}/fxjs
FXJS_MAIN_CMAKELIST_PATH=${ROOT_PATH}/fxjs/program
OUT_PATH=${ROOT_PATH}/out
BIN_ROOT=${ROOT_PATH}/bin
ARCH_DIRNAME=${TARGET_OS}_${TARGET_ARCH}_${BUILD_TYPE}
BIN_PATH=${ROOT_PATH}/bin/${ARCH_DIRNAME}

if [ ${BUILD_TYPE} = 'clean' ]; then
	if [ -e "${OUT_PATH}" ]; then
		rm -rf ${OUT_PATH}
	fi

	if [ -e "${BIN_ROOT}" ]; then
		rm -rf ${BIN_ROOT}
	fi

	exit 0
fi

# [fibjs]Compile project based on fibjs :start
cd ${ROOT_PATH}/fibjs

if [ ! "$BUILD_JOBS" = "" ]; then
    sh build -j${BUILD_JOBS}
else
	sh build -j
fi

if [ ! -e "${OUT_PATH}" ]; then
	mkdir "${OUT_PATH}"
fi

OUT_PATH=${OUT_PATH}/${ARCH_DIRNAME}
if [ ! -e ${OUT_PATH} ]; then
	mkdir ${OUT_PATH}
fi
# [fibjs]Compile project based on fibjs :end

# [fxjs:libs]Compile lib of fxjs :start
OUT_LIB_PATH=${OUT_PATH}/lib
if [ ! -e ${OUT_LIB_PATH} ]; then
	mkdir ${OUT_LIB_PATH}
fi

cd ${OUT_LIB_PATH}
cmake -DBUILD_TYPE=${BUILD_TYPE} -DBUILD_OPTION="${BUILD_OPTION}" ${FXJS_LIB_CMAKELIST_PATH} > CMake.log
if [ $? != 0 ]; then
	exit 1
fi

if [ ! "$BUILD_JOBS" = "" ]; then
	sh -c "${BUILD_VERBOSE} make -j${BUILD_JOBS}"
else
	sh -c "${BUILD_VERBOSE} make"
fi
if [ $? != 0 ]; then
	exit 1
fi
# [fxjs:libs]Compile lib of fxjs :end

# [fxjs:main]Compile main fxjs :start
OUT_MAIN_PATH=${OUT_PATH}/program
if [ ! -e ${OUT_MAIN_PATH} ]; then
	mkdir ${OUT_MAIN_PATH}
fi

cd ${OUT_MAIN_PATH}
cmake ${CMAKE_VARS_2_FXJS_COMPILATION} -DBUILD_TYPE=${BUILD_TYPE} -DBUILD_OPTION="${BUILD_OPTION}" ${FXJS_MAIN_CMAKELIST_PATH} > CMake.log
if [ $? != 0 ]; then
	exit 1
fi

if [ ! "$BUILD_JOBS" = "" ]; then
	sh -c "${BUILD_VERBOSE} make -j${BUILD_JOBS}"
else
	sh -c "${BUILD_VERBOSE} make"
fi
if [ $? != 0 ]; then
	exit 1
fi
# [fxjs:main]Compile main fxjs :end

if [ "${BUILD_TYPE}" = "release" ]; then
	cd "${BIN_PATH}"
	cp "${ROOT_PATH}/installer.txt" "installer.sh"
	tar -zcf fxjs.tar.gz fxjs
	echo '[100%] Built target fxjs.tar.gz'
	cat fxjs.tar.gz >> installer.sh
	chmod 777 installer.sh
	echo '[100%] Built target install.sh'

	if [ $TARGET_OS = "Linux" ]; then
		echo ''
		echo '==== GLIBC ===='
		objdump fxjs -p | grep GLIBC_[0-9.]* -o | sort | uniq
	fi

	if [ "${CI}" = "ci" ]; then
		xz -cz -T2 fxjs > fxjs.xz
		echo '[100%] Built target fxjs.xz'
	fi
fi

cd "${ROOT_PATH}"

txtbld=$(tput bold)
bldred=${txtbld}$(tput setaf 1)
txtrst=$(tput sgr0)

printf "\n\n${bldred}"

printf "${txtrst}"

printf "\\n\\tfxjs has been successfully built.\\n\\n"

# printf "\\tFor more information:\\n\\n"
# printf "\\tfxjs website: http://fxjs.io\\n"
